return {
    SCREEN_WD = 800,
    SCREEN_HT = 600,
    BALL_INIT_SPEED = 200,
    BALL_INC_SPEED = 30,
    BALL_SIZE = 16,
    PLAYER_BASE_SPEED = 200,
    WIN_SCORE = 3,
    BALL_COLOR = { 1, 1, 1, 1 },
    PLAYER_COLOR = { 1, 1, 1, 1 },
    PLAYER_WD = 20,
    PLAYER_HT = 150,
    PLAYER_XOFFSET = 40,
    SCORE_SIZE = 64,
    SCORE_COLOR = { 1, 1, 1, 1 },
    PAUSE_COLOR = { 1, 1, 1, 1 },
    PAUSE_BLINK = 0.7,
    TEXT_SIZE = 80,
    WIN_COLOR = { 1, 1, 1, 1 },
    KEY_UP_PLAYER1 = 'w',
    KEY_DW_PLAYER1 = 's',
    KEY_UP_PLAYER2 = 'i',
    KEY_DW_PLAYER2 = 'k',
    KEY_PAUSE = 'return'
}
